### PR TITLE
Lookup parent coin id

### PR DESCRIPTION
**Pull request by geoffwalmsley**
This adds a function to lookup the parent coin id of the xch spend. It gets the address data from an endpoint at api.aggsig.me/address, and if there are coins at that address it pulls the most recent one (by block_height_confirmed) which matches xch_amount_mojos. 

I've tested it manually, on the xch -> btc workflow, but haven't done a txn with both sides. 

I looked at scraping from explorers, but they all seem to make an ajax call to fetch the coins which makes the scraping approach more complex. It seems like a good use case for an api endpoint, so I created it on a digitalocean server. It should work fine for chiaswap, but is slow when pulling addresses with lots of coins.

### CODE REVIEW

**Comment by richardkiss** [comment]
It sounds like you're writing a web service that does this look-up?

The fact that explorers use an `XMLHttpRequest` kind of thing is actually good. It makes it easier to reverse-engineer the API.

**Comment by richardkiss** [comment]
I dug around a little bit and got these two useful-looking URLs:

https://api2.spacescan.io/1/xch/address/txns/xch18uh2ngsc7dcj5p35xervqrf4nmdqlwk6dtudk62e9aju4ncydhqqmcre0h?page=1&count=10

https://api2.spacescan.io/1/xch/coin/0xb80df1ff70cccfaf72eb449815a81834dc6b3e2516be0f511eb4df9d04c589a9

The first one can be used to find expected payments. The second can find the parent coin.

**Comment by geoffwalmsley** [comment]
Hey, thanks for the feedback. I just added a commit to switch to using spacescan.io. It doesn't have an option to order the txns so we have to fetch all of them every time since the default sorting is oldest first. But like you said, since they're disposable addresses we wouldn't expect a lot of txns. Also wondering if I should add in some validation, eg handling badly formatted addresses?

**Comment by richardkiss** [comment]
Since the use case is to check known valid addresses, I'd say adding address validation in your method would be redundant. We would also reasonably expect the web services API to be able to deal with invalid addresses.

**Comment by richardkiss** [comment]
Also, note that the `address` api actually returns the coin parent id, so for the purposes of `xchswap`, we don't even need the `coin` api!

**Review by richardkiss — APPROVED** [review]

**Pull request merged**
